### ISSUE TITLE
2 D measurements, 3 D state

### ISSUE THREAD

**Issue by PaulStafford1** [rlabbe/filterpy#25] opened 2015-10-01 21:57 UTC
first, thanks $1M for such an incredible book and set of tools - I had despaired of using Kalman filtering until I discovered them. Second, I am a lapsed C programmer, last active 10 years ago, and have been recently learning Python so as to use this library. Sorry if my inexperience is the cause of my issue.

I am trying to implement the following KF: dim x = 3 (pos, vel, acc), dim z = 2 (pos, acc)  - (PS- tried to attach file but it failed):
# x dim 3- spot, vel and acc,
# z dim = 2, spot and acc
f = KalmanFilter (dim_x=3, dim_z=2)
 f.x = np.array([[1.58],         # init position
                            [0.01],     # init velocity
                            [0.0]])      # init acceleration
f.F = np.array([[1.,1., 0.5],   # 1,  delta T, delta T^2/2    timestep = 1
                           [0.,1., 1.],  # 0,  1,       delta T
                           [0.,0., 1.]]) # 0,  0,       1
f.H = np.array([[1.,0., 0.],	       # dim_z by dim_x, i.e. 2 x 3
                        [0.,0., 1.]])	# measure position, and acc, but not vel
f.P = np.array([[1.,0., 0.],	# covariance dim_x dim_x, i.e. 3 x 3
                        [0.,1., 0.],
                        [0.,0., 1.]])
f.R = np.array([[1.,0.],    # measurement noise dim_z dim_z, i.e 2 x 2
                        [0.,1.]])  
f.B = 0 # no control inputs
f.Q = Q_discrete_white_noise(dim=3, dt=1, var=0.5)

my measurements are stored in a .csv file as follows:
pos1, acc1,
pos 2, acc2,
etc

it actually runs for one cycle, then gives a dimensional error. the first estimate is quite incorrect
Thanks for any guidance

**Comment by rlabbe** [comment] 2015-10-01 22:35
I would need to see all the code, but I am going to guess that the dimension of z in your update call is incorrect. As your filter is designed z must be a column vector. If you passed in a row vector the shape of f.x would be wrong after the first update, and subsequent calls would crash.

z = np.array([[1., 0.]]).T # correct
z = np.array([[1., 0.]]).T #incorrect
z = [1., 0.] # incorrect

**Comment by PaulStafford1** [comment] 2015-10-02 14:33
Hi Roger,

Thanks for your reply. I understand that Z needs to be a column vector, and
have tried to make that as explicit in the code as you've illustrated.
Still getting errors which are almost certainly dimensional ones.

I've attached the code (stripped of everything extraneous) and the
measurements data file. If you'd be so kind as to take a 5 min look, I'd be
very grateful!


Paul Stafford


01 (406) 546-8410


<http://www.currencyriskmanagement.com>

**Comment by rlabbe** [comment] 2015-10-02 16:57
sorry, I do not see an attachment.

**Comment by PaulStafford1** [comment] 2015-10-02 18:26
Hi Roger

Attachments dont seem to work properly so I created a Github Gist:
https://gist.github.com/PaulStafford1/83391943d756ea66b2c4
aka PaulStafford1 <https://gist.github.com/PaulStafford1>/*4dtest1.txt
<https://gist.github.com/PaulStafford1/83391943d756ea66b2c4>*


Paul Stafford


01 (406) 546-8410


<http://www.currencyriskmanagement.com>

**Comment by rlabbe** [comment] 2015-10-02 18:43
Your gist runs fine if I comment out the assignment to z inside the loop (I don't have access to your csv data.

I don't see an assert, or any test that z is the correct shape in your code.

    # -*- coding: utf-8 -*-
    """
    Created on Fri Oct  2 11:39:52 2015
    
    @author: rlabbe
    """
    
    import csv
    import sys
    import numpy as np
    import matplotlib.pyplot as plt
    
    from filterpy.kalman import KalmanFilter
    from filterpy.common import Q_discrete_white_noise
    
    for arg in sys.argv[1:]:
        filename = arg   # filename without .csv
    
    # set up KF model.
    # x dim = 3: pos, vel and acc,
    # z dim = 2: pos and acc
    
    f = KalmanFilter (dim_x=3, dim_z=2)
    
    f.x = np.array([[1.58],     # init position
                    [0.01],     # init velocity
                    [0.0]])     # init Acceleration
    
    
    f.F = np.array([[1.,1., 0.5], # 1,  delta T, delta T^2/2
                    [0.,1., 1.],  # 0,  1,       delta T
                    [0.,0., 1.]]) # 0,  0,       1
    
    f.H = np.array([[1.,0., 0.],	# dim_z by dim_x, i.e. 2 x 3
                    [0.,0., 1.]])	# measuring position, and acc, not vel
    
    f.P = np.array([[1.,0., 0.],	# covariance dim_x dim_x, i.e. 3 x 3
                    [0.,1., 0.],
                    [0.,0., 1.]])
    
    f.R = np.array([[1.,0.],    # measurement noise dim_z dim_z, i.e 2 x 2
                    [0.,1.]])
    
    
    f.B = 0 		# no control inputs
    
    f.Q = Q_discrete_white_noise(dim=3, dt=1, var=0.5)
    
    # read position and acc measurements from csv file (pos in col 0, acc in col 1)
    
    
    
    z = np.array([[0.],	# 2x 1 matrix holds one pair of pos and acc measurements
                  [0.]])
    
    # run filter
    for item in range(0,10):
        f.predict()			# first prediction is from initialization data
    
        #z = t_indata[:,item]
        f.update(z)			# update with measurements
        print('yay')

**Comment by rlabbe** [comment] 2015-12-25 20:02
Haven't received any response, assuming everything is fine. Please reopen with reproducible code if this remains a problem.

**Comment by PaulStafford1** [comment] 2015-12-25 22:13
Hi Roger,

Thanks for staying in touch on this, you're very gracious. The truth is
that
a) I am confused about why my data array is not formatted correctly
(columns vs rows) so as not to screw up the matrix math, and did not want
to waste *your *time with such a trivial problem whose solution would also
not be of interest to others.

b)  I had to set the project aside for some more urgent items, but plan on
returning to it in the new year. Our company may have access to additional
funding from the UK government for this project around the March timeframe,
so there will be some urgency by then!

Your FilterPy routines and pdf book are great resources, and I hope to
solve this on my own when I return to it.  If I am unable to after a strong
effort, I"ll reopen.

Happy Holidays


Paul Stafford


01 (406) 546-8410


<http://www.currencyriskmanagement.com>

**Comment by rlabbe** [comment] 2015-12-25 22:19
Forming the correct shape for z is pretty nonintuitive. It needs to be the same shape as the result of the multiplication Hx due to the equation y = z - Hx. Maybe that will help.

I also just checked in a change to KalmanFilter which does more extensive testing on the shape of all matrices. The function test_matrix_dimensions() may let you figure out your problem. 

Don't worry about 'wasting' my time. If you are having problems no doubt others are also, or there is a bug in my code that is not accepting correctly dimensioned arrays. If you can give me exact code and data to reproduce this, I can probably figure it out in just a minute or two.

**Comment by PaulStafford1** [comment] 2015-12-25 22:25
Thanks very much, Roger

Its good to know its non-trivial...
I will review the code and use the test_matrix_dimension() function to
debug, and will revert with results sometime next week.

If the above tests don't help, I'll share the exact code and data and we'll
figure it out.

best regards


Paul Stafford


01 (406) 546-8410


<http://www.currencyriskmanagement.com>

**Comment by PaulStafford1** [comment] 2015-12-29 18:31
Hi Roger

I have successfully run the KF code using a 2nd degree model (pos, vel and
acc) and just position measurements. The code is in 3d1mtest.py, the data
is 1Ddata.csv

The problem is where I add a velocity measurement. Forming each z from the
2 D array is where I'm having trouble. The code is in 3d2mtest.py, the data
is in 2Dposvel.csv, where column a is pos, col b is velocity.

Hopefully the problem will be evident to you in a minute or two :)
thanks in advance!


Paul Stafford


01 (406) 546-8410


<http://www.currencyriskmanagement.com>

**Comment by rlabbe** [comment] 2015-12-29 19:41
I don't know where those files are.

**Comment by PaulStafford1** [comment] 2015-12-29 23:03
sorry, I tried to reply and attach them to the email, which didn't work

see this public github gist, with 2 data files and two Python files
https://gist.github.com/PaulStafford1/4d0fbfc32e732ebe7993


Paul Stafford


01 (406) 546-8410


<http://www.currencyriskmanagement.com>

**Comment by rlabbe** [comment] 2015-12-31 17:58
z needs to be a column vector, such as [[1.], [3.]], whereas you are representing it as [1., 3.]. 

Easiest way to change your code is to write 
    
    for z in input_data:
        z = z.reshape(2,1)  
        f.predict()			
        f.update(z)
        xs.append(f.x[0])  
        vs.append(f.x[1])

The reshape converts z to the correct column format.

As an aside, I wrestle with this interface design. Internally all of the KF code is using column vectors: K and y (the residual) are both column vectors. So, z needs to be a column vector as well. But should I expect the user to know that? Yes, if you end up using KalmanFilter.K or KalmanFilter.y. Maybe not if somebody is just trying to whip something together. I *could* notice that you have passed in a 1D array and silently convert it to a column vector for you. Is that doing the user a favor or disservice? Hard for me to say.

In any case the last few commits to FilterPy adds a lot more assertions and tests. When I ran your code I got an assertion that the shape of z should be (2,1), not (2,). That should be helpful. 

Also note that your shape of H is incorrect. We create a measurement from the state with the multiplication Hx, thus Hx must also be a column vector of shape 2x1. H needs to be 2x3 so that multiplying by a 3x1 matrix the result is 2x1:
    f.H = np.array([[1., 0., 0.],  [0., 1., 0.]])

**Comment by PaulStafford1** [comment] 2015-12-31 18:52
Thanks very much, Roger

I understand, and look forward  to making  those changes and trying it!

Happy New Year


Paul Stafford


01 (406) 546-8410


<http://www.currencyriskmanagement.com>

**Comment by PaulStafford1** [comment] 2015-12-31 20:04
Hi Roger

Addressing those two issues fixed it. (you can close the issue)

In retrospect, my *main *problem was the malformed f.H matrix...

I knew z needed to be a column vector and had originally defined it as  =
np.empty((2,1)). I had some confusion about how Python was reading it off
the input data (I'm an old C programmer from way back, Python is very new
to me), and in my last iteration had simply tried z as a 1,2 vector to see
if that fixed it. dumb.

I'm excited now to be working on the more interesting and important things
like stability and convergence, and optimal initialization of the Q matrix.
After that, I will be attempting to integrate multiple sensors, which in my
application is my real core interest.

You write: " I *could* notice that you have passed in a 1D array and
silently convert it to a column vector for you. Is that doing the user a
favor or disservice? Hard for me to say."
I would reply that because your approach in the ebook is (thankfully)
pedagogical and real-world, silently correcting errors  would be a
disservice to the purpose.

Thanks again for your time and tutoring.



Paul Stafford


01 (406) 546-8410


<http://www.currencyriskmanagement.com>

**Comment by rlabbe** [comment] 2015-12-31 20:06
Glad it all worked out. Knowing the stumbling points is important to me so I can provide better documentation or behavior in the code.

**Closed by rlabbe** 2015-12-31 20:06 UTC
