### ISSUE TITLE
KF and UKF smoother give different result on linear problem

### ISSUE THREAD

**Issue by gboehl** [rlabbe/filterpy#97] opened 2018-04-15 09:38 UTC
Hi,

I am using the UKF to estimate a series of shocks in some time series data using a nonlinear model with a large state space. To become familiar with the tool, I was playing around with a small linear state model with an exogenous AR(1) shock where the state of the AR(1) process is unknown to the observer. For testing I set the observation cov to near-zero. While both filters and the KF-smother gave correct estimates of both the system state and the hidden AR(1) state, the UKF-smoother is only relatively close.

Is this a bug or did I do something wrong?

I uploaded a stylized testing file here: https://github.com/gboehl/zlb_fg_qe/blob/master/test_ukf.py

Thanks for the great work!

**Comment by rlabbe** [comment] 2018-04-15 14:56
Hmm ... mu_kf - mu_ukf returns nearly zero (alternatively np.isclose(mu_kf, mu_ukf) returns all True), whereas x_kf - x_ukf returns significant differences. This points to a bug, or at least unexpected behavior,  in the rts smoother. 

We can see that the RTS is doing its 'best' to smooth out what are valid changes to the process due to the exogenous shock. The issue here (I think) is that the shock applied to an AR(p>0) model applies that shock infinitely far into the past - only the AR(0) model produces white noise. So my first guess is that the UKF might be dealing with the autocorrelated noise better because it is sampling from the distribution. sig_t seems quite large (1) compared to the 

If I switch sig_o = .25 we can see the effect better. I've modified your plotting code just a bit to make the important stuff stand out:

ax2.plot(x_ukf[:,1], marker='o')
ax2.plot(x_kf[:,1], marker='x')

With sig_o=.25 we can see both the KF and UKF trying to smooth the shock. When sig_o << 1, the KF has no choice but to accept the observations as correct compared to the process model, and it tracks the signal. Te UKF is sampling with the sigma points, and I'm guessing this lets it 'see' the autocorrelation, which it tries to smooth into uncorrelated data.

I'm not much of a signals guy - let me know if that makes no sense.

Your code is clean - mind if I incorporate it into a test function, with credit, for FilterPy, if it turns out to be a bug?

**Comment by gboehl** [comment] 2018-04-15 16:07
Thanks for your response!

I assume that both smoothers should return the exact same result since the second (and first) order approximation of a linear system is the linear system. The true state space is two dimensional and the both filters (correctly) keeps track of the hidden second state. For that reason I don't think that the fact that the AR(1) model tracks shocks in the infinite past is an issue.

Note that there is a difference between mu_kf[:,1] and x_kf[:,1] (likewise for mu_ukf & x_ukf): in eonomics you would coin mu_kf[:,1] as _end-of- period notation_ and x_kf[:,1] as _beginning-of-period notation_. However the filtered and smoothed series for state no. 1, mu_kf[:,0] and x_kf[:,0]  are identical. That sort of confused me.

You are of course very welcome to take my code and you are completely right that I in fact meant to write simply X_true (as in X_true[:], it is a one dimensional object) in the plotting snip.

**Comment by rlabbe** [comment] 2018-04-15 17:25
It is not merely required that the systems be linear. It is also required that the Markov property exists (that state X_k depends solely on state x_k-1), and that the noise is white. I.e, there cannot be autocorrelation between states. In this case the states are autocorrelated, and the noise is not white due to the exogenous shock. The plain KF will not perform well. I think we are coming to opposite conclusions; I don't think this is a bug, I think this is the UKF appropriately performing differently in the face of autocorrelation, lack of the Markov property, and non-white noise. 

Please understand I am "babbling" - this is not my area. Wikipedia to the rescue:

> or an AR(1) process with a positive {\displaystyle \varphi } \varphi , only the previous term in the process and the noise term contribute to the output. If {\displaystyle \varphi } \varphi  is close to 0, then the process still looks like white noise, but as {\displaystyle \varphi } \varphi  approaches 1, the output gets a larger contribution from the previous term relative to the noise. This results in a "smoothing" or integration of the output, similar to a low pass filter.

and

> Because each shock affects X values infinitely far into the future from when they occur, any given value Xt is affected by shocks occurring infinitely far into the past. 

https://en.wikipedia.org/wiki/Autoregressive_model

This is unfortunately not very well covered in most of the literature; I'm digging through some books. 

Googling around suggests that your state needs to incorporate shocks into the state. For example: https://ocw.mit.edu/courses/economics/14-384-time-series-analysis-fall-2013/lecture-notes/MIT14_384F13_lec22.pdf  in the "Potential difficulties of MLE for DSGE" section. Note that is more or less unreadable to me, other than to note that the shocks pose considerable difficulties with no clear answers. I have no idea (!) if this applies to your simple example.

In any case, I'm comparing my code to other implementations, as I am not really mathematically equipped to answer the specifics of this use case.  I do not eyeball any errors, but I suppose I should write some tests to better ensure I am happy with my implementation. If you are at all interested, this is the canonical paper on the UKF RTS: https://users.aalto.fi/~ssarkka/pub/uks-preprint.pdf

**Comment by rlabbe** [comment] 2018-04-15 23:02
I made life simpler for myself - I wrote a simple constant velocity kinematic filter and indeed, the RTS give different results.

**Comment by rlabbe** [comment] 2018-04-16 04:57
I pushed a potential fix to master. I need to write unit tests and perhaps do more work before I am satisfied and close this, but now x_kf - x_ukf yields numbers around 1e-10 in all matrix positions with your code example.

**Comment by gboehl** [comment] 2018-04-16 08:55
Thanks a lot! I confirm that the smoother is also working on a larger (linear) model.

**Comment by rlabbe** [comment] 2018-04-17 19:43
I've added a unit test for this problem. It passes. Released in version 1.2.4.

**Closed by rlabbe** 2018-04-17 19:43 UTC
